dailystuff/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('addservice/<int:service_id>/', views.add_to_cart, name='add_to_cart'),
    path('', views.cart_detail, name="cart_detail"),
]

dailystuff/dailystuff/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from servicecatalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicecatalog/', include('servicecatalog.urls')),
    path('searchresult/', include('search_service.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('account/create/', views.registerView, name="register"),
    path('account/login/', views.loginView, name="login"),
    path('account/logout/', views.logoutView, name="logout"),
    path('reviews/', include('reviews.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dailystuff/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('servicereviews/<int:service_id>/', views.serviceReviews, name='serviceReviews'),
    path('add_review_rating/<int:service_id>/', views.addReviewRating, name='addReviewRating'),
]

dailystuff/servicecatalog/urls.py
from django.urls import path
from . import views

app_name = 'servicecatalog'

urlpatterns = [
    path('home/', views.allServiceProducts, name='allServices'),
    path('services/<slug:s_url_key>/', views.serviceByCategory, name='serviceByCategory'),
    path('service/<slug:service_cat_url_key>/<slug:service_prod_url_key>/',
         views.serviceDetail, name="serviceDetail"),
    path('accounts/create/', views.loginView, name='loginview'),
]

dailystuff/servicecatalog/models.py
from django.db import models
from django.urls import reverse


class ServiceCategory(models.Model):
    category_name = models.CharField(max_length=250, unique=True)
    url_key = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='servicecategory', blank=True)

    class Meta:
        ordering = ('category_name',)
        verbose_name = 'Service Category'
        verbose_name_plural = 'Service Categories'

    def __str__(self):
        return '{}'.format(self.category_name)

    def get_url(self):
        return reverse('servicecatalog:serviceByCategory', args=[self.url_key])


class ServiceProduct(models.Model):
    product_name = models.CharField(max_length=250, unique=True)
    url_key = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='serviceproduct', blank=True)
    servicecategory = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE)
    service_cost = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    popularity = models.IntegerField(default=0)

    class Meta:
        ordering = ('product_name',)
        verbose_name = 'Service Product'
        verbose_name_plural = 'Service Products'

    def __str__(self):
        return '{}'.format(self.product_name)

    def get_url(self):
        return reverse('servicecatalog:serviceDetail',
                       args=[self.servicecategory.url_key, self.url_key])

dailystuff/servicecatalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=120, required=True)
    last_name = forms.CharField(max_length=120, required=True)
    email = forms.EmailField(max_length=250, help_text='eg. someemail@domain.com')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2')

dailystuff/servicecatalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
from .models import ServiceCategory, ServiceProduct
from .forms import RegisterForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout


def allServiceProducts(request):
    " Get All Service Products "
    service_list = ServiceProduct.objects.raw(
        'SELECT * FROM servicecatalog_serviceproduct where is_available=1'
    )
    paginator = Paginator(service_list, 6)
    try:
        page_num = int(request.GET.get('page', 1))
    except:
        page_num = 1
    try:
        services = paginator.page(page_num)
    except (EmptyPage, InvalidPage):
        services = paginator.page(paginator.num_pages)
    return render(request, 'servicecatalog/services.html', {'category': None, 'services': services})


def serviceByCategory(request, s_url_key):
    " Get Service Products by Service Category"
    s_page = get_object_or_404(ServiceCategory, url_key=s_url_key)
    service_list = ServiceProduct.objects.raw(
        'SELECT * FROM servicecatalog_serviceproduct where is_available=1 '
        'and servicecategory_id={}'.format(s_page.id)
    )
    paginator = Paginator(service_list, 6)
    try:
        page_num = int(request.GET.get('page', 1))
    except:
        page_num = 1
    try:
        services = paginator.page(page_num)
    except (EmptyPage, InvalidPage):
        services = paginator.page(paginator.num_pages)
    return render(request, 'servicecatalog/services.html', {'category': s_page, 'services': services})


def serviceDetail(request, service_cat_url_key, service_prod_url_key):
    try:
        service = ServiceProduct.objects.get(servicecategory__url_key=service_cat_url_key,
                                             url_key=service_prod_url_key)
        popular = ServiceProduct.objects.all().order_by('popularity')[:5]
    except Exception as e:
        raise e
    return render(request, 'servicecatalog/serviceproduct.html', {'service': service, 'popular': popular})


def registerView(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            register_user = User.objects.get(username=username)
            user_group = Group.objects.get(name='Customer')
            user_group.user_set.add(register_user)
    else:
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})


def loginView(request):
    if request.method == 'POST':
        form  = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                print("user password right............")
                login(request, user)
                return redirect('servicecatalog:allServices')
            else:
                return redirect('register')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logoutView(request):
    logout(request)
    return redirect('login')

dailystuff/servicecatalog/templates/servicecatalog/commonbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">

    <title>{% block pagetitle %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
            {% include 'topsection-navbar.html' %}
        </div>
        {% include 'headersection.html' %}
        {% include 'navigationbar.html' %}
        {% block maincontent %}
        {% endblock %}
    </div>
    {% include 'footersection.html' %}
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

dailystuff/servicecatalog/templates/servicecatalog/serviceproduct.html
{% extends 'servicecatalog/commonbase.html' %}
{% load static %}
{% block metadescription %}
    {{ service.description|truncatewords:155 }}
{% endblock %}
{% block pagetitle %}
    {{ service.product_name }} - Daily Stuff
{% endblock %}
{% block maincontent %}
    <div class="row my_prod_row_class">
        <div class="mx-auto">
            <p><a href="{% url 'servicecatalog:allServices' %}">Home</a> |
                <a href="{{ service.servicecategory.get_url }}">{{ service.servicecategory.category_name}}</a>
                | {{ service.product_name }}</p>
        </div>
        <div class="container">
            <br>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <div style="min-width: 18rem;">
                        <img style="width: 100%;" src="{{ service.image.url }}" alt="{{ service.product_name }}">
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                    <div>
                        <h1 class="my_prod_title">{{ service.product_name }}</h1>
                        <p>${{ service.service_cost }}</p>
                        <p class="text-justify my_prod_text">Product Description</p>
                        <p>{{ service.description }}</p>
                        <p><a href="{% url 'reviews:serviceReviews' service.id %}">View Reviews</a></p>
                        {% if service.stock <= 0 %}
                            <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
                        {% else %}
                            <a class="btn btn-secondary" href="{% url 'cart:add_to_cart' service.id %}">
                                Add to Cart
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dailystuff/servicecatalog/templates/servicecatalog/services.html
{% extends 'servicecatalog/commonbase.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to the cushion store where you can buy comfy and awesome cushions.
    {% endif %}
{% endblock %}
{% block pagetitle %}
    {% if category %}
        {{ category.name }} - Perfect Cushion Store
    {% else %}
        See Our Cushion collection - Perfect Cushion Store
    {% endif %}
{% endblock %}
{% block maincontent %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'servicecatalog:allServices' %}">Our Service Collection</a> | {{ category.category_name }}</p>
            </div>
        </div>
    {% endif %}
    <div class="mx-auto">
        {% if category %}
            <img class="my_image" src="{{ category.image.url }}" alt="{{ category.category_name }}">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{ category.name }}</h1>
        <p class="text-justify">{{ category.description }}</p>
    </div>
    {% else %}
        <img class="my_image my_image_padding" src="{% static 'images/banner.jpg' %}" alt="Our Services Collection">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">Our Services Collection</h1>
        <p class="text-justify">Finding perfect cushion for your room can instantly add to the levels of comfort and
        sense of style throughout your home. They can transform the blandest of decors instantly by adding colour,
        softness and an air of cosiness.</p>
    </div>
    {% endif %}
    <div class="container">
        <div class="row mx-auto">
            {% for service in services.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                    <div class="card text-center" style="width: 18rem;">
                        <a href="{{ service.get_url }}">
                            <img class="card-img-top my_image" src="{{ service.image.url }}" alt="{{service.name}}">
                            <div class="card-body">
                                <h4>{{ service.product_name }}</h4>
                                <p>${{ service.service_cost }}</p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if services.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in services.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if services.number == pg%}active{%endif%}">{{pg}}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <br>
    </div>

{% endblock %}