dailystuff/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('addservice/<int:service_id>/', views.add_to_cart, name='add_to_cart'),
    path('', views.cart_detail, name="cart_detail"),
]

dailystuff/dailystuff/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from servicecatalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicecatalog/', include('servicecatalog.urls')),
    path('searchresult/', include('search_service.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('account/create/', views.registerView, name="register"),
    path('account/login/', views.loginView, name="login"),
    path('account/logout/', views.logoutView, name="logout"),
    path('reviews/', include('reviews.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dailystuff/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('servicereviews/<int:service_id>/', views.serviceReviews, name='serviceReviews'),
    path('add_review_rating/<int:service_id>/', views.addReviewRating, name='addReviewRating'),
]

dailystuff/reviews/models.py
from django.db import models
from servicecatalog.models import ServiceProduct


class ServiceReviews(models.Model):
    service = models.ForeignKey(ServiceProduct, on_delete=models.CASCADE)
    customer_id = models.IntegerField()
    review_comment = models.TextField(max_length=500)
    rating = models.IntegerField(default=1)
    posted_on = models.DateTimeField(auto_now_add=True)

dailystuff/reviews/views.py
from django.shortcuts import render, get_object_or_404, redirect
from servicecatalog.models import ServiceProduct
from .models import ServiceReviews
from django.http import HttpResponse


def serviceReviews(request, service_id):
    can_add_review = True
    service = ServiceProduct.objects.get(id=service_id)
    service_reviews = ServiceReviews.objects.all().filter(service_id=service_id)
    # avg_rating = ServiceReviews.objects.raw('SELECT avg(rating) FROM reviews_servicereviews')
    if request.user.is_authenticated:
        customer_review = ServiceReviews.objects.all().filter(service_id=service_id, customer_id=request.user.id)
        if customer_review:
            can_add_review = False
    context = {
        'service': service,
        'service_reviews': service_reviews,
        'can_add_review': can_add_review
    }
    return render(request, 'reviews.html', context)

def addReviewRating(request, service_id):
    ratingValue = request.POST['rating']
    reviewComment = request.POST['comment']
    userId = request.POST['user_id']
    service = get_object_or_404(ServiceProduct, id=service_id)
    serviceReview = ServiceReviews.objects.create(
        service=service,
        customer_id=userId,
        review_comment=reviewComment,
        rating=ratingValue
    )
    serviceReview.save()
    return redirect('reviews:serviceReviews', service_id)

dailystuff/reviews/templates/reviews.html
{% extends 'servicecatalog/commonbase.html' %}
{% load static %}
{% block metadescription %}
    This is Service Review Page
{% endblock %}
{% block pagetitle %}
    Service Reviews - Daily Stuff
{% endblock %}
{% block maincontent %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width: 18rem;">
                    <img style="width: 100px;height: 100px;" src="{{ service.image.url }}" alt="{{ service.product_name }}">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div class="rating-block">
                    <h2 class="my_prod_title">{{ service.product_name }}</h2>
                    <h4>Average user rating</h4>
                    <h2 class="bold padding-bottom-7">4.3 <small>/ 5</small></h2>
                </div>
                <div>
                    {% if request.user.is_authenticated %}
                        {% if can_add_review %}
                        <button class="open-button" onclick="openForm()">Write a review</button>
                        <div class="form-popup" id="myForm">
                            <form action="{% url 'reviews:addReviewRating' service.id %}" class="form-container" id="reviewform" method="post">
                                {% csrf_token %}
                                <fieldset class="rating">
                                    <legend>Please rate:</legend>
                                    <input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="Rocks!">5 stars</label>
                                    <input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
                                    <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="Meh">3 stars</label>
                                    <input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="Kinda bad">2 stars</label>
                                    <input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="Sucks big time">1 star</label>
                                </fieldset>
                                <label for="comment"><b>Review Comment</b></label>
                                <textarea name="comment" form="reviewform" placeholder="Your Comment here" required></textarea>
                                <input type="hidden" value="{{request.user.id}}" name="user_id">
                                <button type="submit" class="btn">Submit</button>
                                <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
                            </form>
                        </div>
                        {% else %}
                        <p>You have already added a review</p>
                        {% endif %}
                    {% else %}
                        <p>Please Login to write a review</p>
                    {% endif %}
                </div>
            </div>
        </div>
            {% if service_reviews %}
                {% for review in service_reviews %}
                    <div class="row">
                        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                            <h2>Added by customer {{review.customer_id}}</h2>
                        </div>
                        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                            <p>{{ review.review_comment }}</p>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No Reviews for this product yet..</p>
            {% endif %}
    </div>
<script>
function openForm() {
  document.getElementById("myForm").style.display = "block";
}

function closeForm() {
  document.getElementById("myForm").style.display = "none";
}
</script>
{% endblock %}