dailystuff/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('addservice/<int:service_id>/', views.add_to_cart, name='add_to_cart'),
    path('', views.cart_detail, name="cart_detail"),
]

dailystuff/dailystuff/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from servicecatalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicecatalog/', include('servicecatalog.urls')),
    path('searchresult/', include('search_service.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('account/create/', views.registerView, name="register"),
    path('account/login/', views.loginView, name="login"),
    path('account/logout/', views.logoutView, name="logout"),
    path('reviews/', include('reviews.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dailystuff/search_service/urls.py
from django.urls import path
from . import views

app_name = 'search_service'

urlpatterns = [
    path('', views.fullPageResult, name='fullPageResult'),
]

dailystuff/servicecatalog/urls.py
from django.urls import path
from . import views

app_name = 'servicecatalog'

urlpatterns = [
    path('home/', views.allServiceProducts, name='allServices'),
    path('services/<slug:s_url_key>/', views.serviceByCategory, name='serviceByCategory'),
    path('service/<slug:service_cat_url_key>/<slug:service_prod_url_key>/',
         views.serviceDetail, name="serviceDetail"),
    path('accounts/create/', views.loginView, name='loginview'),
]

dailystuff/servicecatalog/models.py
from django.db import models
from django.urls import reverse


class ServiceCategory(models.Model):
    category_name = models.CharField(max_length=250, unique=True)
    url_key = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='servicecategory', blank=True)

    class Meta:
        ordering = ('category_name',)
        verbose_name = 'Service Category'
        verbose_name_plural = 'Service Categories'

    def __str__(self):
        return '{}'.format(self.category_name)

    def get_url(self):
        return reverse('servicecatalog:serviceByCategory', args=[self.url_key])


class ServiceProduct(models.Model):
    product_name = models.CharField(max_length=250, unique=True)
    url_key = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='serviceproduct', blank=True)
    servicecategory = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE)
    service_cost = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    popularity = models.IntegerField(default=0)

    class Meta:
        ordering = ('product_name',)
        verbose_name = 'Service Product'
        verbose_name_plural = 'Service Products'

    def __str__(self):
        return '{}'.format(self.product_name)

    def get_url(self):
        return reverse('servicecatalog:serviceDetail',
                       args=[self.servicecategory.url_key, self.url_key])

dailystuff/servicecatalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=120, required=True)
    last_name = forms.CharField(max_length=120, required=True)
    email = forms.EmailField(max_length=250, help_text='eg. someemail@domain.com')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2')

dailystuff/servicecatalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
from .models import ServiceCategory, ServiceProduct
from .forms import RegisterForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout


def allServiceProducts(request):
    " Get All Service Products "
    service_list = ServiceProduct.objects.raw(
        'SELECT * FROM servicecatalog_serviceproduct where is_available=1'
    )
    paginator = Paginator(service_list, 6)
    try:
        page_num = int(request.GET.get('page', 1))
    except:
        page_num = 1
    try:
        services = paginator.page(page_num)
    except (EmptyPage, InvalidPage):
        services = paginator.page(paginator.num_pages)
    return render(request, 'servicecatalog/services.html', {'category': None, 'services': services})


def serviceByCategory(request, s_url_key):
    " Get Service Products by Service Category"
    s_page = get_object_or_404(ServiceCategory, url_key=s_url_key)
    service_list = ServiceProduct.objects.raw(
        'SELECT * FROM servicecatalog_serviceproduct where is_available=1 '
        'and servicecategory_id={}'.format(s_page.id)
    )
    paginator = Paginator(service_list, 6)
    try:
        page_num = int(request.GET.get('page', 1))
    except:
        page_num = 1
    try:
        services = paginator.page(page_num)
    except (EmptyPage, InvalidPage):
        services = paginator.page(paginator.num_pages)
    return render(request, 'servicecatalog/services.html', {'category': s_page, 'services': services})


def serviceDetail(request, service_cat_url_key, service_prod_url_key):
    try:
        service = ServiceProduct.objects.get(servicecategory__url_key=service_cat_url_key,
                                             url_key=service_prod_url_key)
        popular = ServiceProduct.objects.all().order_by('popularity')[:5]
    except Exception as e:
        raise e
    return render(request, 'servicecatalog/serviceproduct.html', {'service': service, 'popular': popular})


def registerView(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            register_user = User.objects.get(username=username)
            user_group = Group.objects.get(name='Customer')
            user_group.user_set.add(register_user)
    else:
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})


def loginView(request):
    if request.method == 'POST':
        form  = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                print("user password right............")
                login(request, user)
                return redirect('servicecatalog:allServices')
            else:
                return redirect('register')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logoutView(request):
    logout(request)
    return redirect('login')

dailystuff/servicecatalog/templates/footersection.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">copy: Daily Stuff. All Rights Reserved</p>
</div>

dailystuff/servicecatalog/templates/headersection.html
{% load static %}
<header>
    <center>
        <a href="{% url 'servicecatalog:allServices' %}"><img src="{% static 'images/logo.png' %}" alt="Daily Stuff Store"></a>
    </center>
</header>

dailystuff/servicecatalog/templates/navigationbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Services
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'servicecatalog:allServices' %}">All Services</a>
                    {% for cat in menulinks %}
                    <a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.category_name }}</a>
                    {% endfor %}
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                    <i class="fas fa-shopping-cart"></i>({% if item_count > 0 %}{{item_count}}{% endif %})
                </a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'search_service:fullPageResult' %}" method="get">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </div>
</nav>

dailystuff/servicecatalog/templates/topsection-navbar.html
<div class="container">
    <div class="my_custom_menu">
        <ul>
            {% if request.user.is_authenticated and request.user.first_name %}
            <li>
                Welcome, {{ request.user.first_name }}<i class="fas fa-user-circle"></i>
            </li>
            <li>
                <a href="{% url 'logout' %}">Sign Out<i class="fas fa-sign-out-alt"></i></a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'register' %}">Sign Up<i class="fas fa-user-plus"></i></a>
            </li>
            <li>
                <a href="{% url 'login' %}">Sign In<i class="fas fa-sign-in-alt"></i></a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>