dailystuff/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('addservice/<int:service_id>/', views.add_to_cart, name='add_to_cart'),
    path('', views.cart_detail, name="cart_detail"),
]

dailystuff/dailystuff/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from servicecatalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicecatalog/', include('servicecatalog.urls')),
    path('searchresult/', include('search_service.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('account/create/', views.registerView, name="register"),
    path('account/login/', views.loginView, name="login"),
    path('account/logout/', views.logoutView, name="logout"),
    path('reviews/', include('reviews.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dailystuff/servicecatalog/urls.py
from django.urls import path
from . import views

app_name = 'servicecatalog'

urlpatterns = [
    path('home/', views.allServiceProducts, name='allServices'),
    path('services/<slug:s_url_key>/', views.serviceByCategory, name='serviceByCategory'),
    path('service/<slug:service_cat_url_key>/<slug:service_prod_url_key>/',
         views.serviceDetail, name="serviceDetail"),
    path('accounts/create/', views.loginView, name='loginview'),
]

dailystuff/cart/models.py
from django.db import models
from servicecatalog.models import ServiceProduct


class Quote(models.Model):
    quote_id = models.CharField(max_length=300, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Quote'
        ordering = ['date_added']

    def __str__(self):
        return self.quote_id


class QuoteItem(models.Model):
    service = models.ForeignKey(ServiceProduct, on_delete=models.CASCADE)
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'QuoteItem'

    def sub_total(self):
        return self.service.service_cost * self.quantity

    def __str__(self):
        return self.service

dailystuff/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from servicecatalog.models import ServiceProduct
from .models import Quote, QuoteItem
import stripe
from django.conf import settings
from orders.models import Order, OrderItem


def _quote_id(request):
    quote = request.session.session_key
    if not quote:
        quote = request.session.create()
    return quote

def add_to_cart(request, service_id):
    service = ServiceProduct.objects.get(id=service_id)
    try:
        quote = Quote.objects.get(quote_id=_quote_id(request))
    except Quote.DoesNotExist:
        quote = Quote.objects.create(
            quote_id=_quote_id(request)
        )
        quote.save()
    try:
        quote_item = QuoteItem.objects.get(service=service, quote=quote)
        if quote_item.quantity < quote_item.service.stock:
            quote_item.quantity += 1
        quote_item.save()
    except QuoteItem.DoesNotExist:
        quote_item = QuoteItem.objects.create(
            service = service,
            quote = quote,
            quantity = 1
        )
        quote_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request, order_total=0, counter=0, quote_items=0):
    try:
        quote = Quote.objects.get(quote_id=_quote_id(request))
        quote_items = QuoteItem.objects.filter(quote=quote, active=True)
        for quote_item in quote_items:
            order_total += (quote_item.service.service_cost * quote_item.quantity)
            counter += quote_item.quantity
    except ObjectDoesNotExist:
        pass
    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_total = int(order_total * 100)
    description = 'Daily Stuff - New Order'
    data_key = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        try:
            stripeToken = request.POST['stripeToken']
            stripeEmail = request.POST['stripeEmail']
            stripeBillingName = request.POST['stripeBillingName']
            stripeBillingAddressLine1 = request.POST['stripeBillingAddressLine1']
            stripeBillingAddressCity = request.POST['stripeBillingAddressCity']
            stripeBillingAddressZip = request.POST['stripeBillingAddressZip']
            stripeBillingAddressCountryCode = request.POST['stripeBillingAddressCountryCode']
            stripeShippingName = request.POST['stripeShippingName']
            stripeShippingAddressLine1 = request.POST['stripeShippingAddressLine1']
            stripeShippingAddressCity = request.POST['stripeShippingAddressCity']
            stripeShippingAddressZip = request.POST['stripeShippingAddressZip']
            stripeShippingAddressCountryCode = request.POST['stripeShippingAddressCountryCode']
            customer = stripe.Customer.create(
                email = stripeEmail,
                source = stripeToken
            )
            charge = stripe.Charge.create(
                amount = stripe_total,
                currency = 'gbp',
                description = description,
                customer = customer.id
            )
            # saving order in admin code here
            try:
                LoggedInCustomer = None
                if request.user.is_authenticated:
                    LoggedInCustomer = request.user.id
                orderDetails = Order.objects.create(
                    token=stripeToken,
                    total=stripe_total,
                    email_id=stripeEmail,
                    billingName=stripeBillingName,
                    billingAddress1=stripeBillingAddressLine1,
                    billingCity=stripeBillingAddressCity,
                    billingPostcode=stripeBillingAddressZip,
                    billingCountry=stripeBillingAddressCountryCode,
                    shippingName=stripeShippingName,
                    shippingAddress1=stripeShippingAddressLine1,
                    shippingCity=stripeShippingAddressCity,
                    shippingPostcode=stripeShippingAddressZip,
                    shippingCountry=stripeShippingAddressCountryCode,
                    customerId=LoggedInCustomer
                )
                orderDetails.save()
                for quote_item in quote_items:
                    order_item = OrderItem.objects.create(
                        product=quote_item.service.product_name,
                        quantity=quote_item.quantity,
                        price=quote_item.service.service_cost,
                        order=orderDetails
                    )
                    order_item.save()
                    '''Reduce the stock when the order is placed or saved'''
                    serviceProduct = ServiceProduct.objects.get(id=quote_item.service.id)
                    serviceProduct.stock = int(quote_item.service.stock - quote_item.quantity)
                    serviceProduct.popularity += 1
                    serviceProduct.save()
                    '''Remove the item from the shopping cart'''
                    quote_item.delete()
                return redirect('orders:thankspage', orderDetails.id)
            except ObjectDoesNotExist:
                pass
        except stripe.error.CardError as e:
            return False, e
    return render(request, 'cart_detail.html', dict(
        quote_items=quote_items,
        total=order_total,
        counter=counter,
        data_key=data_key,
        stripe_total=stripe_total,
        description=description
    ))

dailystuff/cart/templates/cart_detail.html
{% extends 'servicecatalog/commonbase.html' %}
{% load static %}
{% block metadescription %}
    This is Shopping Cart Page
{% endblock %}
{% block pagetitle %}
    Cart - Daily Stuff
{% endblock %}
{% block maincontent %}
    {% if not quote_items %}
    <div>
        <div class="text-center">
            <h1 class="text-center my_title">
                Your Shopping Cart is Empty
            </h1>
            <br>
            <p class="text-center">
                Please click <a href="{% url 'servicecatalog:allServices' %}">here</a> to continue shopping
            </p>
        </div>
    </div>
    {% else %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">
                Your Shopping Cart
            </h1>
            <br>
        </div>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                        <th colspan="5">
                            Your Items
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for quote_item in quote_items %}
                        <tr>
                            <td>
                                <a href="{{quote_item.service.get_url}}">
                                    <img src="{{quote_item.service.image.url}}" alt="" class="float-left rounded custom_image">
                                </a>
                            </td>
                            <td class="text-left">
                                {{quote_item.service.product_name}}
                                <br>
                                SKU: {{quote_item.service.id}}
                                <br>
                                Unit Price: {{quote_item.service.service_cost}}
                                <br>
                                Qty: {{quote_item.quantity}} x ${{quote_item.service.service_cost}}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Review your shopping cart and proceed to checkout
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Your total is: {{total}}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <form action="" method="POST">
                    {% csrf_token %}
                    <script
                        src = "https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key = {{data_key}}
                        data-amount = {{stripe_total}}
                        data-name = "Perfect Cushion Shop"
                        data-description = {{description}}
                        data-image = "{% static 'images/logo.png' %}"
                        data-locale = "auto"
                        data-currency = "gbp"
                        data-shipping-address = "true"
                        data-billing-address = "true"
                        data-zip-code = "true">
                    </script>
                </form>
                <a href="{% url 'servicecatalog:allServices' %}" class="btn btn-secondary btn-block my_custom_button">
                    Continue Shopping
                </a>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}